# BASE <%= base_image %>
FROM <%= dockerfile_name %>
<% env_vars.each do |env| -%>
ENV <%= env %>
<% end -%>
ADD chef/ /etc/chef/
<% if include_credentials -%>
RUN chef-init --bootstrap --no-remove-secure
<% else -%>
RUN chef-init --bootstrap
<% end -%>
ENTRYPOINT ["chef-init"]
CMD ["--onboot"]
