# BASE <%= base_image %>
FROM <%= dockerfile_name %>
ADD chef/ /etc/chef/
<% if include_credentials -%>
RUN chef-init --bootstrap --no-remove-secure
<% else -%>
RUN chef-init --bootstrap
<% end -%>
ENTRYPOINT ["chef-init"]
CMD ["--onboot"]
